version: "3.8"
services:
  auth-backend:
    image: turismosai/sai-auth:10.9.0
    container_name: turismo-sai-auth-back
    hostname: auth-back
    env_file:
      - ./auth.env
    ports:
      - 8881:8881
    volumes:
      - ./auth-storage:/home/node/app/storage:rw
    networks:
      - turismo-sai-net
    restart: unless-stopped
    extra_hosts:
      - "host.docker.internal:host-gateway"
  pw-backend:
    image: turismosai/sai-pw-back:7.6.0
    container_name: turismo_sai_pw-backend
    hostname: pw-back
    env_file:
      - ./pw-backend.env
    ports:
      - 8882:8882
    networks:
      - turismo-sai-net
    restart: unless-stopped
    extra_hosts:
      - "host.docker.internal:host-gateway"
  pw-frontend:
    image: turismosai/sai-pw-front:12.4.0
    container_name: turismo_sai_frontend
    hostname: pw-frontend
    env_file:
      - ./pw-frontend.env
    working_dir: /app
    ports:
      - "${APP_PORT:-3000}:3000"
    volumes:
      - ./pw-frontend-storage:/app/storage:rw
    # environment:
    #   NODE_ENV: ${PW_FRONT_NODE_ENV:-development}
    #   NEXT_PUBLIC_STORAGE: ${NEXT_PUBLIC_STORAGE:?err}
    #   NEXT_PUBLIC_AUTH_SERVICE: ${NEXT_PUBLIC_AUTH_SERVICE:?err}
    #   NEXT_PUBLIC_SAI_SERVICE_BACKEND: ${NEXT_PUBLIC_SAI_SERVICE_BACKEND:?err}
    networks:
      - turismo-sai-net
    restart: unless-stopped
    extra_hosts:
      - "host.docker.internal:host-gateway"
  minio:
    image: minio/minio:latest
    container_name: minio
    env_file:
      - ./auth.env
    # environment:
    #   - MINIO_ACCESS_KEY=${MINIO_ACCESS_KEY:?err}
    #   - MINIO_SECRET_KEY=${MINIO_SECRET_KEY:?err}
    ports:
      - "9000:9000"
      - "9001:9001"
    command: server /data --console-address ":9001"
    volumes:
      - 'minio_data:/data'
    networks:
      - turismo-sai-net
    extra_hosts:
      - "host.docker.internal:host-gateway"
networks:
  turismo-sai-net:
    driver: bridge

volumes:
  minio_data:
    driver: local